apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: api-gateway
  ports:
    - port: 80
      targetPort: {{ .Values.services.apiGateway.port }}
