apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: auth-service
  ports:
    - port: 80
      targetPort: {{ .Values.services.auth.port }}
