apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: "{{ .Values.services.auth.image }}:{{ .Values.services.auth.tag }}"
          ports:
            - containerPort: {{ .Values.services.auth.port }}

          env:
            - name: PORT
              value: "{{ .Values.services.auth.port }}"

            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD

            - name: DB_NAME
              value: "auth_db"

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET

          readinessProbe:
            httpGet:
              path: {{ .Values.global.readinessProbe.httpGet.path }}
              port: {{ .Values.services.auth.port }}
            initialDelaySeconds: {{ .Values.global.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.global.readinessProbe.failureThreshold }}

          livenessProbe:
            httpGet:
              path: {{ .Values.global.livenessProbe.httpGet.path }}
              port: {{ .Values.services.auth.port }}
            initialDelaySeconds: {{ .Values.global.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.global.livenessProbe.periodSeconds }}

          resources:
            requests:
              cpu: {{ .Values.global.resources.requests.cpu }}
              memory: {{ .Values.global.resources.requests.memory }}
            limits:
              cpu: {{ .Values.global.resources.limits.cpu }}
              memory: {{ .Values.global.resources.limits.memory }}