apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: content-service
  ports:
    - port: 80
      targetPort: {{ .Values.services.content.port }}
