---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-backend
  labels:
    app: vetaorigin
    tier: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production-backend
  labels:
    app: vetaorigin
    tier: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app: vetaorigin
    tier: monitoring
